name: Generate Custom EPG

on:
  schedule:
    # Run every 07:00 WIB (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual execution via GitHub Actions button

jobs:
  grab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run EPG Grabber
        run: |
	  mkdir -p public
          npm run grab -- \
            -c my_channels.xml \
            -o docs/epg.xml \
            -d 2000 \
            --maxConnections 1

      - name: Compress EPG File to .gz
        run: gzip -c docs/epg.xml > docs/epg.xml.gz

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add my_channels.xml docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Custom EPG [skip ci]" && git push)
